name: Selenium Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20'  # Specify the desired Java version here

      - name: Build with Maven
        run: mvn package

      - name: Run Selenium tests
        run: mvn test
